services:
  # openssh
  minecraft_openssh:
    image: linuxserver/openssh-server:latest
    container_name: minecraft_openssh
    profiles:
      - minecraft_openssh
    depends_on:
      - mc-server
    restart: on-failure:5
    env_file:
      - ./openssh/env/openssh.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - minecraft_openssh_config:/config
      - ./openssh/config/authorized_keys:/authorized_ssh_keys:ro
    networks:
      - minecraft_network
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - SYS_ADMIN
    ports:
      - 2222:2222

volumes:
  minecraft_openssh_config:
    name: minecraft_openssh_config
  mc-data: 
    name: mc-data
  mc-backup:
    name: mc-backup
  mc-rcon:
    name: mc-rcon
  mc-proxy:
    name: mc-proxy
