services:
  # openssh
  minecraft_openssh:
    image: linuxserver/openssh-server:latest
    container_name: minecraft_openssh
    profiles:
      - minecraft_openssh
    depends_on:
      - mc-server
    restart: on-failure:5
    env_file:
      - ./openssh/env/openssh.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - minecraft_serve_openssh_config:/config
      - ./openssh/config/authorized_keys:/authorized_ssh_keys:ro
      - minecraft_server_data:/minecraft_server_data
      - minecraft_proxy_data:/minecraft_proxy_data
      - minecraft_server_backup:/minecraft_server_backup
      - minecraft_rcon_data:/minecraft_rcon_data
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - SYS_ADMIN
    ports:
      - 2222:2222

volumes:
  minecraft_serve_openssh_config:
    name: minecraft_serve_openssh_config
  minecraft_server_backup:
    name: minecraft_server_backup
  minecraft_server_data:
    name: minecraft_server_data
  minecraft_proxy_data:
    name: minecraft_proxy_data
  minecraft_rcon_data:
    name: minecraft_rcon_data
