services:
  # openssh
  mc-openssh:
    image: linuxserver/openssh-server:latest
    container_name: mc-openssh
    profiles:
      - mc-openssh
    depends_on:
      - mc-server
    restart: on-failure:5
    env_file:
      - ./openssh/env/openssh.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - mc-openssh-config:/config
      - ./openssh/config/authorized_keys:/authorized_ssh_keys:ro
      - ./minecraft-server/mc-data:/mc-data
      - ./minecraft-server/mc-proxy:/mc-proxy
      - ./backup/mc-backup:/mc-backup
    networks:
      - minecraft_network
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - SYS_ADMIN
    ports:
      - 2222:2222

volumes:
  mc-openssh-config:
    name: mc-openssh-config
