services:
  # openssh
  mc-openssh:
    image: linuxserver/openssh-server:latest
    container_name: mc-openssh
    profiles:
      - mc-openssh
    depends_on:
      - mc-server
    restart: on-failure:5
    env_file:
      - ./openssh/env/openssh.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - minecraft_serve_openssh_config:/config
      - ./openssh/config/authorized_keys:/authorized_ssh_keys:ro
      - ./mc-data:/mc-data
      - ./mc-proxy:/mc-proxy
      - ./backup/mc-backup:/mc-backup
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:false
    cap_drop:
      - SYS_ADMIN
    ports:
      - 2222:2222

volumes:
  minecraft_serve_openssh_config:
    name: minecraft_serve_openssh_config
  minecraft_server_backup:
    name: minecraft_server_backup
  minecraft_server_data:
    name: minecraft_server_data
  minecraft_server_config:
    name: minecraft_server_config
  minecraft_server_log:
    name: minecraft_server_log
