version: "3.8"

services:
  monitor:
    image: itzg/mc-monitor:latest
    restart: on-failure:3
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: "mc,mc-blitz"
      DEBUG: "true"
    depends_on:
      - mc
      - mc-blitz
  prometheus:
    image: prom/prometheus:latest
    restart: on-failure:3
    # Disable port because there is grafana.
    #    ports:
    #      - 9090:9090
    volumes:
      - ./mc-monitor/examples/mc-monitor-prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.4}
    restart: on-failure:3
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./mc-monitor/examples/mc-monitor-prom/grafana/provisioning:/etc/grafana/provisioning
      - ./mc-monitor/examples/mc-monitor-prom/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
volumes:
  prometheus-tsdb: {}
  grafana-lib: {}
