version: "3.8"

services:
  web:
    image: itzg/rcon:latest
    restart: on-failure:3
    depends_on:
      - mc
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: mc
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
    ports:
      - 4326:4326
      - 4327:4327
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
  mc:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: on-failure:3
    ports:
      - 25565:25565
      #       For Dynmap
      - 8123:8123
    environment:
      #       Server options
      EULA: "true"
      ONLINE_MODE: "true"
      SERVER_PORT: "25565"
      # TYPE: PAPER
      TYPE: PURPUR
      SERVER_NAME: "MyServer"
      MOTD: "My Server"
      VERSION: "1.18.1"
      MEMORY: 8G
      EXEC_DIRECTLY: "false"
      USE_AIKAR_FLAGS: "true"
      USE_LARGE_PAGES: "false"
      #      TUNE_VIRTUALIZED: "true"
      CONSOLE: "false"
      TZ: "Europe/Paris"
      OPS: "Bensuperpc"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "3600"
      OVERRIDE_SERVER_PROPERTIES: "true"
      MAX_TICK_TIME: "-1"
      GUI: "false"
      # Time (sec) before AFK player was disconect
      PLAYER_IDLE_TIMEOUT: "240"
      MAX_PLAYERS: "100"
      MODE: "survival"
      ALLOW_FLIGHT: "false"
      #       RCON options
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: "25575"
      BUILD_FROM_SOURCE: "false"
      # Plugins options
      # 274 = Dynmap
      # 390 = Multiverse-Core
      # 9089 = EssentialsX
      # 28140 = LuckyPerm
      # 34315 = Vault
      # 32748 = Set Home
      # 81534 = Chunky
      # 8631 = CoreProtect
      # 67701 = BanItems
      # 1997 = ProtocolLib
      # 13932 = Fast Async WorldEdit
      SPIGET_RESOURCES: "274"
      #      MODPACK: "http://dev.bukkit.org/projects/worldedit/files/latest,http://dev.bukkit.org/projects/timber-plugin/files/latest"
      #      Minecraft option
      LEVEL: world
      LEVEL_TYPE=: "default"
      #      MAX_WORLD_SIZE: "10000"
      #      MAX_BUILD_HEIGHT: "256"
      VIEW_DISTANCE: "12"
      ENABLE_COMMAND_BLOCK: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      PVP: "true"
      DIFFICULTY: hard
      HARDCORE: "false"
      ALLOW_NETHER: "true"
      # Spawn Entities Options
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: "16"
      #      SEED: "-1785852800490497919"
      SNOOPER_ENABLED: "true"
    volumes:
      - mc-data:/data
  backups:
    image: itzg/mc-backup:latest
    restart: on-failure:3
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "8h"
      INITIAL_DELAY: "3m"
      PRUNE_BACKUPS_DAYS: "7"
      PAUSE_IF_NO_PLAYERS: "true"
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    volumes:
      # mount the same volume used by server, but read-only
      - mc-data:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ./mc-backups:/backups
    # share network namespace with server to simplify rcon access
    network_mode: "service:mc"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: on-failure:3
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  monitor:
    image: itzg/mc-monitor:latest
    restart: on-failure:3
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    depends_on:
      - mc
  prometheus:
    image: prom/prometheus:latest
    restart: on-failure:3
    # Disable port because there is grafana.
    #    ports:
    #      - 9090:9090
    volumes:
      - ./mc-monitor/examples/mc-monitor-prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    restart: on-failure:3
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./mc-monitor/examples/mc-monitor-prom/grafana/provisioning:/etc/grafana/provisioning
      - ./mc-monitor/examples/mc-monitor-prom/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  mc-data: {}
  rcon: {}
  prometheus-tsdb: {}
  grafana-lib: {}
