version: "3.8"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: on-failure:3
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
