services:
  mc-proxy:
    image: itzg/bungeecord:latest
    container_name: minecraft-proxy-server
    profiles:
      - mc-proxy
    restart: on-failure:3
    env_file:
      - ./minecraft-server/env/proxy.env
    environment:
      INIT_MEMORY: "512M"
      MAX_MEMORY: "2048M"
    ports:
      #       Server Minecraft port
      - "25565:25577"
      #       Server Minecraft Bedrock port (GeyserMC)
      #- "19132:19132/udp"
      #       Rcon port
      #- "25576:25575"
      #       Plan port
      # - "8806:8804"
    volumes:
      - ./minecraft-server/mc-proxy:/server
    networks:
      - minecraft_network

  mc-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    profiles:
      - mc-server
      - mc-server-main
    depends_on:
      - mc-proxy
    restart: on-failure:3
    ports:
      #       Server Minecraft port (Disable if you use proxy)
      # - "25565:25565"
      #       Rcon port
      # - "25575:25575"
      #       Server Minecraft Bedrock port (GeyserMC)
      # - "19132:19132/udp"
      #       Dynmap port
      # - "8123:8123"
      #       BlueMap port
      - "8100:8100"
      #       Plan port
      - "8804:8804"
    env_file:
      - ./minecraft-server/env/server.env
      - ./minecraft-server/env/world.env
      - ./minecraft-server/env/mods_plugins.env
    environment:
      MAX_MEMORY: "${MAX_MEMORY:-24G}"
    volumes:
      - ./minecraft-server/mc-data:/data
#      - ./minecraft-server/asset_links/plugins.txt:/extras/plugins.txt:ro
    networks:
      - minecraft_network
    deploy:
      resources:
#        limits:
#          cpus: '8.0'
#          memory: 26G
        reservations:
          cpus: '0.01'
          memory: 20M

  rcon-web:
    image: itzg/rcon:latest
    container_name: minecraft-rcon-web
    profiles:
      - mc-web
    restart: on-failure:3
    depends_on:
      - mc-server
      - mc-proxy
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc-server' compose service below
      RWA_RCON_HOST: mc-server
      RWA_RCON_PASSWORD: 6hxU3Oxmh2Q8e6S9fjkdWJikRCON_PASSWORD
    ports:
      #       web UI port
      - "4326:4326"
      #       websocket access from UI
      - "4327:4327"
    volumes:
      - ./minecraft-server/mc-rcon:/opt/rcon-web-admin/db
    networks:
      - minecraft_network

volumes:
  mc-data: 
    name: mc-data
  mc-rcon:
    name: mc-rcon
  mc-proxy:
    name: mc-proxy

networks:
  minecraft_network:
    driver: bridge
    name: minecraft_network
