services:
  mc-backup:
    image: mazzolino/restic:latest
    container_name: mc-backup
    profiles:
      - mc-backup
    depends_on:
      - mc-server
      - mc-proxy
    restart: on-failure:3
    env_file:
      - ./env/backup.env
    volumes:
      - ./backup/mc-backup:/mnt/restic
      - ./minecraft-server/mc-data:/data/mc-data:ro
      - ./minecraft-server/mc-proxy:/data/mc-proxy:ro
    security_opt:
      - no-new-privileges:true
    network_mode: none
    cap_drop:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN

volumes:
  mc-backup:
    name: mc-backup
