version: "3.8"

services:
  router:
    image: ${MC_ROUTER_IMAGE:-itzg/mc-router}
    container_name: minecraft-proxy-server
    profiles:
      - mc-router
    restart: on-failure:3
    depends_on:
      - vanilla
    environment:
      # enable API
      API_BINDING: ":25564"
    ports:
      - 25565:25565
      # bind the API port to only loopback to avoid external exposure
      - 127.0.0.1:25564:25564
    command: --mapping=vanilla.example.com=vanilla:25565,minecraft.bensuperpc.fr=vanilla:25565
  vanilla:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    profiles:
      - mc-server
      - mc-server-main
    depends_on:
      - mc-router
    restart: on-failure:3
    env_file:
      - env/server.env
      - env/world.env
    #      - env/mods_plugins.env
    environment:
      MAX_MEMORY: "${MAX_MEMORY:-12G}"
    volumes:
      - mc-data:/data
  #      - ./asset_links/plugins.txt:/extras/plugins.txt:ro
  backups:
    image: itzg/mc-backup:latest
    container_name: minecraft-backup
    profiles:
      - mc-backup
      - mc-backup-main
    restart: on-failure:3
    depends_on:
      - vanilla
    env_file:
      - env/backup.env
    environment:
      # instead of network_mode below, could declare RCON_HOST
      RCON_HOST: vanilla
      BACKUP_NAME: "server-main"
    volumes:
      # mount the same volume used by server, but read-only
      - mc-data:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      #- ./mc-backups:/backups
      - mc-backups:/backups
    # share network namespace with server to simplify rcon access
    # network_mode: "service:mc"
  rcon-web:
    image: itzg/rcon:latest
    container_name: minecraft-rcon-web
    profiles:
      - mc-web
    restart: on-failure:3
    depends_on:
      - vanilla
      - mc-router
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: vanilla
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
    ports:
      #       web UI port
      - "4326:4326"
      #       websocket access from UI
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"
volumes:
  mc-data: {}
  mc-backups: {}
  rcon: {}
