name: docker-minecraft-server

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev"
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 9 * * 2" # every tuesday at 9:00 https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:

jobs:
  image:
    name: docker-minecraft-server
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3.0.2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: "Build server"
        run: MAX_MEMORY=3G docker-compose -f docker-compose.yml build
      - name: "Start server"
        run: ./start.sh
      - name: "Wait..."
        run: sleep 480
      - name: "Check minecraft port"
        if: always()
        run: nc -zv 127.0.0.1 25565
      - name: "Check rcon port"
        if: always()
        run: nc -zv 127.0.0.1 25575
      - name: "Check web rcon port"
        if: always()
        run: nc -zv 127.0.0.1 4326
      - name: "Check server"
        if: always()
        run: docker-compose -f docker-compose.yml top
      - name: "Check logs server"
        if: always()
        run: docker-compose -f docker-compose.yml logs
      - name: "Stop containers"
        if: always()
        run: ./stop.sh
