name: docker-minecraft-server

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev"
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 9 * * 2" # every tuesday at 9:00 https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:

jobs:
  image:
    name: docker-minecraft-server
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3.3.0
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: "Start server"
        run: make start
      - name: "Wait..."
        run: sleep 480
      - name: "Check minecraft port"
        if: always()
        run: nc -zv 127.0.0.1 25565
      - name: "Check rcon port"
        if: always()
        run: nc -zv 127.0.0.1 25575
      - name: "Check web rcon port"
        if: always()
        run: nc -zv 127.0.0.1 4326
      - name: "Check server"
        if: always()
        run: make state
      - name: "Check logs server"
        if: always()
        run: make logs
      - name: "Stop containers"
        if: always()
        run: make stop
      - name: "Remove containers"
        if: always()
        run: make down